const API='https://iptv-org.github.io/api';
const categoryInfo={animation:['Animação','🎨'],auto:['Automóveis','🚗'],business:['Negócios','💼'],classic:['Clássicos','📼'],comedy:['Comédia','😂'],cooking:['Culinária','🍳'],culture:['Cultura','🎭'],documentary:['Documentários','🌎'],education:['Educação','📚'],entertainment:['Entretenimento','✨'],family:['Família','👨‍👩‍👧‍👦'],general:['Geral','📺'],kids:['Infantil','🧸'],legislative:['Legislativo','🏛️'],lifestyle:['Estilo de vida','🌿'],movies:['Filmes','🎬'],music:['Música','🎵'],news:['Notícias','📰'],outdoor:['Natureza','🏕️'],relax:['Relaxamento','🌙'],religious:['Religião','⛪'],science:['Ciência','🔬'],series:['Séries','🎞️'],shop:['Compras','🛍️'],sports:['Esportes','⚽'],travel:['Viagens','✈️'],weather:['Clima','🌦️']};
const regionNames={AFR:'África',AMER:'Américas',ASI:'Ásia',EUR:'Europa',OCE:'Oceania',ANT:'Antártida'};
const state={countries:[],channels:[],streams:[],available:[],countryMap:new Map(),streamsByChannel:new Map(),favorites:new Set(JSON.parse(localStorage.getItem('bento-tv-favorites')||'[]')),current:null,view:'home',activeCountry:null,activeCategory:null,hls:null};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const el={search:$('#search'),region:$('#region'),sort:$('#sort'),stats:$('#stats'),brazilGrid:$('#brazilGrid'),featuredCountries:$('#featuredCountries'),featuredCategories:$('#featuredCategories'),countriesGrid:$('#countriesGrid'),categoriesGrid:$('#categoriesGrid'),channelsGrid:$('#channelsGrid'),favoritesGrid:$('#favoritesGrid'),searchGrid:$('#searchGrid'),player:$('#player'),placeholder:$('#placeholder'),nowLogo:$('#nowLogo'),nowFallback:$('#nowFallback'),nowTitle:$('#nowTitle'),nowMeta:$('#nowMeta'),favoriteCurrent:$('#favoriteCurrent'),toast:$('#toast'),sectionEyebrow:$('#sectionEyebrow'),sectionTitle:$('#sectionTitle'),sectionDescription:$('#sectionDescription'),channelsTitle:$('#channelsTitle'),channelsDescription:$('#channelsDescription')};
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function flag(code){return code&&code.length===2?[...code.toUpperCase()].map(c=>String.fromCodePoint(127397+c.charCodeAt())).join(''):'🌐';}
function countryName(code){return state.countryMap.get(code)?.name||code||'Mundo';}
function cat(id){return categoryInfo[id]||[id?`${id[0].toUpperCase()}${id.slice(1)}`:'Geral','📺'];}
function toast(msg){el.toast.textContent=msg;el.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove('show'),2800);}
function setView(name){state.view=name;$$('.view').forEach(v=>v.classList.remove('visible'));$(`#${name}View`)?.classList.add('visible');$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name!=='home')$('.catalog').scrollIntoView({behavior:'smooth',block:'start'});}
async function load(){try{const [countries,channels,streams]=await Promise.all(['countries','channels','streams'].map(x=>fetch(`${API}/${x}.json`).then(r=>{if(!r.ok)throw Error(x);return r.json()})));state.countries=countries;state.channels=channels;state.streams=streams;state.countryMap=new Map(countries.map(c=>[c.code,c]));streams.forEach(s=>{if(!s.channel||!s.url)return;if(!state.streamsByChannel.has(s.channel))state.streamsByChannel.set(s.channel,[]);state.streamsByChannel.get(s.channel).push(s)});state.available=channels.filter(c=>state.streamsByChannel.has(c.id));buildRegions();renderAll();toast('Catálogo carregado. O mundo está sintonizado.')}catch(e){console.error(e);el.stats.textContent='Não foi possível carregar o catálogo agora.'}}
function buildRegions(){const regions=[...new Set(state.countries.map(c=>c.region).filter(Boolean))].sort();el.region.innerHTML='<option value="">Todos os continentes</option>'+regions.map(r=>`<option value="${esc(r)}">${esc(regionNames[r]||r)}</option>`).join('');}
function countryCounts(){const m=new Map();state.available.forEach(c=>m.set(c.country,(m.get(c.country)||0)+1));return m;}
function categoryCounts(){const m=new Map();state.available.forEach(c=>(c.categories?.length?c.categories:['general']).forEach(x=>m.set(x,(m.get(x)||0)+1)));return m;}
function countryCard(c){return `<button class="country-card" data-country="${esc(c.code)}"><span class="flag">${flag(c.code)}</span><h4>${esc(c.name)}</h4><p>${c.count.toLocaleString('pt-BR')} canais disponíveis</p></button>`;}
function categoryCard(c){const [name,icon]=cat(c.id);return `<button class="category-card" data-category="${esc(c.id)}"><span class="category-icon">${icon}</span><h4>${esc(name)}</h4><p>${c.count.toLocaleString('pt-BR')} canais</p></button>`;}
function channelCard(c){const cats=(c.categories?.length?c.categories:['general']).slice(0,2).map(x=>cat(x)[0]).join(' · ');const logo=c.logo?`<img loading="lazy" src="${esc(c.logo)}" alt="" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span hidden>TV</span>`:'<span>TV</span>';return `<button class="channel-card" data-channel="${esc(c.id)}"><div class="logo-wrap">${logo}</div><h4>${esc(c.name)}</h4><p>${esc(cats)}</p><div class="channel-foot"><span>${flag(c.country)} ${esc(countryName(c.country))}</span><b>${state.favorites.has(c.id)?'★':'☆'}</b></div></button>`;}
const empty=m=>`<div class="empty"><b>${esc(m)}</b></div>`;
function renderAll(){renderHome();renderCountries();renderCategories();renderFavorites();const cc=countryCounts(),kc=categoryCounts();el.stats.textContent=`${state.available.length.toLocaleString('pt-BR')} canais · ${[...cc.values()].length} países · ${kc.size} assuntos`;}
function renderHome(){el.brazilGrid.innerHTML=state.available.filter(c=>c.country==='BR').slice(0,8).map(channelCard).join('')||empty('Nenhum canal brasileiro disponível agora.');const cc=countryCounts();el.featuredCountries.innerHTML=['BR','US','AR','PT','MX','CA','JP','FR'].map(code=>{const c=state.countryMap.get(code);return c?{...c,count:cc.get(code)||0}:null}).filter(c=>c&&c.count).map(countryCard).join('');const kc=categoryCounts();el.featuredCategories.innerHTML=['news','sports','music','education','documentary','kids','business','travel'].map(id=>({id,count:kc.get(id)||0})).filter(c=>c.count).map(categoryCard).join('');}
function renderCountries(){const cc=countryCounts();let rows=state.countries.map(c=>({...c,count:cc.get(c.code)||0})).filter(c=>c.count);if(el.region.value)rows=rows.filter(c=>c.region===el.region.value);rows.sort(el.sort.value==='count'?(a,b)=>b.count-a.count||a.name.localeCompare(b.name):(a,b)=>a.name.localeCompare(b.name));el.countriesGrid.innerHTML=rows.map(countryCard).join('')||empty('Nenhum país encontrado.');}
function renderCategories(){const kc=categoryCounts();let rows=[...kc].filter(([id])=>id!=='xxx').map(([id,count])=>({id,count}));rows.sort(el.sort.value==='count'?(a,b)=>b.count-a.count||cat(a.id)[0].localeCompare(cat(b.id)[0]):(a,b)=>cat(a.id)[0].localeCompare(cat(b.id)[0]));el.categoriesGrid.innerHTML=rows.map(categoryCard).join('')||empty('Nenhum assunto encontrado.');}
function renderFavorites(){const rows=state.available.filter(c=>state.favorites.has(c.id));el.favoritesGrid.innerHTML=rows.map(channelCard).join('')||empty('Você ainda não favoritou nenhum canal.');}
function openCountry(code){const rows=state.available.filter(c=>c.country===code).sort((a,b)=>a.name.localeCompare(b.name));state.activeCountry=code;state.activeCategory=null;const name=countryName(code);el.channelsTitle.textContent=`${flag(code)} ${name}`;el.channelsDescription.textContent=`${rows.length.toLocaleString('pt-BR')} canais disponíveis`;el.channelsGrid.innerHTML=rows.map(channelCard).join('')||empty('Nenhum canal disponível nesse país.');el.sectionEyebrow.textContent='PAÍS';el.sectionTitle.textContent=name;el.sectionDescription.textContent='Todos os canais disponíveis desse país.';setView('channels');}
function openCategory(id){const rows=state.available.filter(c=>c.categories?.includes(id)).sort((a,b)=>a.name.localeCompare(b.name));state.activeCategory=id;state.activeCountry=null;const [name,icon]=cat(id);el.channelsTitle.textContent=`${icon} ${name}`;el.channelsDescription.textContent=`${rows.length.toLocaleString('pt-BR')} canais disponíveis`;el.channelsGrid.innerHTML=rows.map(channelCard).join('')||empty('Nenhum canal disponível nesse assunto.');el.sectionEyebrow.textContent='ASSUNTO';el.sectionTitle.textContent=name;el.sectionDescription.textContent='Canais reunidos por assunto.';setView('channels');}
function play(id){const c=state.available.find(x=>x.id===id),s=state.streamsByChannel.get(id)?.[0];if(!c||!s)return toast('Esse canal não possui transmissão disponível.');state.current=c;el.placeholder.style.display='none';el.nowTitle.textContent=c.name;el.nowMeta.textContent=`${flag(c.country)} ${countryName(c.country)} · ${(c.categories||[]).slice(0,2).map(x=>cat(x)[0]).join(' · ')||'TV ao vivo'}`;if(c.logo){el.nowLogo.src=c.logo;el.nowLogo.hidden=false;el.nowFallback.hidden=true}else{el.nowLogo.hidden=true;el.nowFallback.hidden=false}el.favoriteCurrent.textContent=state.favorites.has(c.id)?'★':'☆';document.title=`${c.name} — Bento TV`;attach(s.url);window.scrollTo({top:0,behavior:'smooth'});}
function attach(url){if(state.hls){state.hls.destroy();state.hls=null}el.player.pause();el.player.removeAttribute('src');el.player.load();const hls=/\.m3u8($|\?)/i.test(url);if(hls&&window.Hls?.isSupported()){state.hls=new Hls({enableWorker:true,lowLatencyMode:true});state.hls.loadSource(url);state.hls.attachMedia(el.player);state.hls.on(Hls.Events.MANIFEST_PARSED,()=>el.player.play().catch(()=>{}));state.hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)playError(url)});return}if(el.player.canPlayType('application/vnd.apple.mpegurl')||!hls){el.player.src=url;el.player.play().catch(()=>{});return}playError(url);}
function playError(url){el.placeholder.style.display='grid';el.placeholder.innerHTML=`<span>!</span><b>Este canal bloqueou a reprodução no navegador.</b><a href="${esc(url)}" target="_blank" rel="noopener" style="color:#ffd60a">Abrir transmissão diretamente</a>`;}
function toggleFavorite(id){if(!id)return;if(state.favorites.has(id)){state.favorites.delete(id);toast('Canal removido dos favoritos.')}else{state.favorites.add(id);toast('Canal salvo nos favoritos.')}localStorage.setItem('bento-tv-favorites',JSON.stringify([...state.favorites]));renderFavorites();if(state.current?.id===id)el.favoriteCurrent.textContent=state.favorites.has(id)?'★':'☆';if(state.view==='channels'){if(state.activeCountry)openCountry(state.activeCountry);else if(state.activeCategory)openCategory(state.activeCategory)}}
function random(){if(!state.available.length)return toast('O catálogo ainda está carregando.');const rows=state.available.filter(c=>!c.categories?.includes('xxx'));const c=rows[Math.floor(Math.random()*rows.length)];toast(`IA HAHAHAHA escolheu: ${c.name}`);play(c.id);}
function search(q){const term=q.trim().toLocaleLowerCase('pt-BR');if(!term){setMeta('DESCUBRA','Destaques do mundo','Países, assuntos e canais organizados para você.');return setView('home')}const rows=state.available.filter(c=>[c.name,...(c.alt_names||[]),countryName(c.country),...(c.categories||[]).map(x=>cat(x)[0])].join(' ').toLocaleLowerCase('pt-BR').includes(term)).slice(0,200);setMeta('BUSCA',`Resultados para “${q.trim()}”`,'Mostrando até 200 canais para manter o site rápido.');el.searchGrid.innerHTML=rows.map(channelCard).join('')||empty('Nenhum canal encontrado.');setView('search');}
function setMeta(e,t,d){el.sectionEyebrow.textContent=e;el.sectionTitle.textContent=t;el.sectionDescription.textContent=d;}
document.addEventListener('click',e=>{const country=e.target.closest('[data-country]');if(country)return openCountry(country.dataset.country);const category=e.target.closest('[data-category]');if(category)return openCategory(category.dataset.category);const channel=e.target.closest('[data-channel]');if(channel)return play(channel.dataset.channel);const go=e.target.closest('[data-go]');if(go){if(go.dataset.go==='countries')setMeta('MUNDO','Países','Escolha um país e veja todos os canais.');if(go.dataset.go==='categories')setMeta('ASSUNTOS','Explore por assunto','Notícias, esportes, música, educação e muito mais.');setView(go.dataset.go)}});
$$('.nav').forEach(b=>b.onclick=()=>{const v=b.dataset.view;if(v==='home')setMeta('DESCUBRA','Destaques do mundo','Países, assuntos e canais organizados para você.');if(v==='countries')setMeta('MUNDO','Países','Escolha um país e veja todos os canais.');if(v==='categories')setMeta('ASSUNTOS','Explore por assunto','Notícias, esportes, música, educação e muito mais.');if(v==='favorites'){renderFavorites();setMeta('SALVOS','Favoritos','Seus canais preferidos ficam guardados neste aparelho.')}setView(v)});
$$('[data-random]').forEach(b=>b.onclick=random);el.search.oninput=e=>search(e.target.value);el.region.onchange=()=>{renderCountries();setMeta('MUNDO','Países','Escolha um país e veja todos os canais.');setView('countries')};el.sort.onchange=()=>{renderCountries();renderCategories()};$('#back').onclick=()=>{const v=state.activeCountry?'countries':state.activeCategory?'categories':'home';setView(v)};$('#brazilButton').onclick=()=>openCountry('BR');el.favoriteCurrent.onclick=()=>toggleFavorite(state.current?.id);$('#year').textContent=new Date().getFullYear();load();
